[package]
name = "heitx"
version = "0.1.0"
authors = ["zhaozhenhang <azhzhaozhenhang@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
# set grapheme
unicode-segmentation = "1"
